// <auto-generated />
using System;
using CCRS.Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCRS.Catalog.API.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20240912231157_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCRS.Catalog.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("RecipeDirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Step")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeDirectionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<float>("Stars")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.IngredientDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientMeasureId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeDirectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientMeasureId");

                    b.HasIndex("RecipeDirectionId");

                    b.ToTable("IngredientDirections");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.IngredientMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasureId");

                    b.ToTable("IngredientMeasures");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitLong")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UnitShort")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PublishedBy")
                        .HasColumnType("int");

                    b.Property<int>("ReadyInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.RecipeDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDirections");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Direction", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.RecipeDirection", "RecipeDirection")
                        .WithMany("Directions")
                        .HasForeignKey("RecipeDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipeDirection");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Feedback", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.Recipe", "Recipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.IngredientDirection", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.IngredientMeasure", "IngredientMeasure")
                        .WithMany("IngredientDirections")
                        .HasForeignKey("IngredientMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCRS.Catalog.API.Models.RecipeDirection", "RecipeDirection")
                        .WithMany("IngredientDirections")
                        .HasForeignKey("RecipeDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientMeasure");

                    b.Navigation("RecipeDirection");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.IngredientMeasure", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientMeasures")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCRS.Catalog.API.Models.Measure", "Measure")
                        .WithMany("IngredientMeasure")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Recipe", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.Category", "Category")
                        .WithMany("Recipe")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCRS.Catalog.API.Models.Difficulty", "Difficulty")
                        .WithMany("Recipe")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.RecipeDirection", b =>
                {
                    b.HasOne("CCRS.Catalog.API.Models.Recipe", "Recipe")
                        .WithMany("RecipeDirections")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Category", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Difficulty", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientMeasures");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.IngredientMeasure", b =>
                {
                    b.Navigation("IngredientDirections");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Measure", b =>
                {
                    b.Navigation("IngredientMeasure");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.Recipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RecipeDirections");
                });

            modelBuilder.Entity("CCRS.Catalog.API.Models.RecipeDirection", b =>
                {
                    b.Navigation("Directions");

                    b.Navigation("IngredientDirections");
                });
#pragma warning restore 612, 618
        }
    }
}
